language: python
python:
  - pypy
env:
  - PORTAGE=2.2.14
  - PORTAGE=2.2.17
  - JOB=0
  - JOB=1
  - JOB=2
  - JOB=3
  - JOB=4
  - JOB=5
  - JOB=6
  - JOB=7
  - JOB=8
  - JOB=9
  - JOB=10
  - JOB=11
  - JOB=12
  - JOB=13
  - JOB=14
  - JOB=15

before_script:
    - mkdir travis-overlay
    - mv !(travis-overlay) travis-overlay/
    - mv .git travis-overlay/
    - wget "http://distfiles.gentoo.org/distfiles/portage-$PORTAGE.tar.bz2"
    - wget "http://distfiles.gentoo.org/snapshots/portage-latest.tar.xz"
    - sudo chmod 777 /etc/passwd /etc/group /etc /usr
    - echo "portage:x:250:250:portage:/var/tmp/portage:/bin/false" >> /etc/passwd
    - echo "portage::250:portage,travis" >> /etc/group
    - mkdir -p /etc/portage/ /usr/portage/distfiles
    - tar xjf portage-$PORTAGE.tar.bz2
    - tar xJf portage-latest.tar.xz -C /usr/
    - cp portage-$PORTAGE/cnf/repos.conf /etc/portage/
    - rsync --recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --checksum --quiet rsync://rsync.gentoo.org/gentoo-portage /usr/portage
    - ln -s /usr/portage/profiles/base/ /etc/portage/make.profile
    - cd travis-overlay
    - sed -i 's/fcmd=fcmd/fcmd=("%s -q" % fcmd)/' ./../portage-$PORTAGE/bin/repoman

script:
    - ret=0; cx=0;
      for x in $(cat /usr/portage/profiles/categories); do
      if test $(( cx++ % 16 )) -eq ${JOB}; then
          cd ${x} && {
            python ./../portage-${PORTAGE}/bin/repoman full -v -d -x || ret=1;
          } && cd -;
        fi;
      done;
      exit "${ret}"

notifications:
  irc: "chat.freenode.net#gentoo-science"

